apiVersion: networking.k8s.io/v1
# apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Exact
            backend:
              # serviceName: auth-srv
              # servicePort: 3000
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/payments/?(.*)
            pathType: Exact
            backend:
              # serviceName: payments-srv
              # servicePort: 3000
              service:
                name: payments-srv
                port:
                  number: 3000
          - path: /api/tickets/?(.*)
            pathType: Exact
            backend:
              # serviceName: tickets-srv
              # servicePort: 3000
              service:
                name: tickets-srv
                port:
                  number: 3000
          - path: /api/orders/?(.*)
            pathType: Exact
            backend:
              # serviceName: orders-srv
              # servicePort: 3000
              service:
                name: orders-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Exact
            backend:
              # serviceName: client-srv
              # servicePort: 3000
              service:
                name: client-srv
                port:
                  number: 3000
#thisisunsafe
